# Generated by Django 4.2.9 on 2024-02-22 21:09

from django.db import migrations, models
import imagesearch.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesearch', '0002_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=imagesearch.models.get_file_path),
        ),
    ]
